print("Random Recipe Generator!")
print()
randomFood = input("Name a food > ")
cookingMethod = input("Name a word to describe food > ")
randomDessert = input("Name a random dessert > ")
randomFlavour = input("Name a random flavour > ")
randomVegetable = input("Name a random vegetable > ")
print()
print("Menu:")
print(randomFood,"with a side of",cookingMethod,randomVegetable,",and for dessert,",randomFlavour,randomDessert)