username = input("Choose a username > ")
password = input("Choose a password > ")
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print("SECURE LOGIN SYSTEM")
print()
userName = input("Username > ")
passWord = input("Password > ")
print()
if userName == username and passWord == password:
  print("Welcome,",username,"!", "You have successfully logged in!")
else:
  print("Sorry",userName,", you don't seem to have access.")
  print("Please try again:")
  print()
  userName = input("Username > ")
  passWord = input("Password > ")
  print()
if userName == username and passWord == password:
  print("Welcome,",username,"!", "You have successfully logged in!")
else:
  print("Sorry",userName,", you don't seem to have access.")
  print("Please try again:")
  print()
  userName = input("Username > ")
  passWord = input("Password > ")
  print()
if userName == username and passWord == password:
  print("Welcome,",username,"!", "You have successfully logged in!")
else:
  print("Sorry",userName,", you don't seem to have access.")